### PR TITLE
properly splits filename on all platforms when setting a checkpoint

### LINKED ISSUE #354: Creating checkpoint faild due to wrong class name (include path)
I wanted to create an checkpoint but MM is passing full path instead of class name to query, which causes Malformed query error.

Windows 7 64bit, SublimeText 3, latest MM.

```
Operation: Creating new checkpoint at line 1011...
Timestamp: Fri, 25 Apr 2014 14:22:03
   Result: [OPERATION FAILED]: Server raised fault: 'MALFORMED_QUERY: 
Name From ApexClass Where Name = 'C:\Users\user1\code\mm_workspace\EMS_Canada_Dev\src\classes\Account_Test'
                                ^
ERROR at Row:1:Column:44
Invalid string literal 'C:\Users\user1\code\mm_workspace\EMS_Canada_Dev\src\classes\Account_Test'. Illegal character sequence '\U' in string literal.'
```

### PR DESCRIPTION
**Pull request by daveespo**
closes #354

### CODE REVIEW

**Comment by ralphcallaway** [comment]
thanks @daveespo

**Comment by ralphcallaway** [comment]
light testing completed on os x, confirmed show and hide apex checkpoints worked before and after applying pull request

**Comment by ralphcallaway** [comment]
@daveespo this is available in v4.0.4 which is current available for pre-release, thanks again for the contributions!

**Comment by daveespo** [comment]
Thanks Ralph -- how do I pick up the pre-release via Package Control? Or should I just sit tight until you push it to the stable channel?

**Comment by ralphcallaway** [comment]
@daveespo package control has a setting, `install_prereleases` ([docs](https://packagecontrol.io/docs/settings)) where you can specify a list of a packages you want to install pre-releases for 

that said, it looks like I might not have this set up quite right yet. this is the first time we've done a pre-release and either i'm not waiting long enough for package control to recognize their is an update, or they want me to flag the release differently

in any event, if you set the pre-release flag you should get a package control message with the change log when it's installed (or just wait another week or so and it'll become a regular release)

**Comment by ralphcallaway** [comment]
@daveespo was able to get the pre-release to pull down after removing and reinstalling the package (still will only come down if you update your package control settings per the prior comment)

any chance you could update your settings and see if you're able to get the pre-release to install without removing the package? just curious whether the issue was just a caching issue on my machine, or whether package control is hitting an error when trying to upgrade to the pre-release (clean installs seem to work fine)

**Comment by daveespo** [comment]
I'm not succeeding even after removing and reinstalling via Package Control -- this is what my Package Control.sublime_settings looks like:

````
{
	"install_prereleases":
	[
		"MavensMate"
	],
	"installed_packages":
	[
		"MavensMate",
		"Package Control"
	]
}
````

According to the package-metadata.json, it's still 4.0.3

When I close all of my open files in Sublime, then restart Sublime, this is what goes by in the console .. and I promise, I don't have the settings file open in any other editor 

````
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
Package Control: Installing 1 upgrades
Exception in thread Thread-8:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "package_control.automatic_upgrader in C:\Users\esposito\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 198, in do_upgrades
  File "package_control.package_manager in C:\Users\esposito\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 749, in install_package
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\esposito\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\Package Control.sublime-package'

reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
````

You don't need to kill yourself puzzling on this one -- I can wait until the package hits the stable channel -- but if there's anything else obvious I should try, I'm game to give it a go

**Comment by ralphcallaway** [comment]
@daveespo very strange, in my own testing it seems like things eventually just work (also corrected the about page so if you go to about mavens mate you'll see v4.0.4, still waiting on that to hit the cache), as of today it was able to upgrade without issue to the pre-release

did some quick googling and saw this https://github.com/wbond/package_control/issues/796

you might try upgrading package control itself first, since the issue says the windows permissions error was fixed last december

in any event, if that doesn't work this will be a full release within the next week or so

**Comment by daveespo** [comment]
Sorry I dropped the ball on this .. you know how it goes

Summarizing: Yes, upgrading Package Control to v3.0.1. solved the problem. I was able to install MavensMate 4.0.4-prerelease.2

And yes, the problem with setting checkpoints on Windows has been resolved.

Thanks!

**Pull request merged**
