### PR TITLE
Ability to retrieve templates from Bitbucket and Github, including private repos

### PR DESCRIPTION
**Pull request by jamesmelville**
Stores passwords in the clear as sublime does not include keyring module
Not tested on Linux
Fixes joeferraro/MavensMate#313
Dependent on joeferraro/mm#30

### CODE REVIEW

**Comment by ralphcallaway** [comment]
thanks @jamesmelville

**Comment by ralphcallaway** [comment]
@jamesmelville this is available in v4.0.4 which is current available for pre-release, thanks again for the contributions!

**Comment by ralphcallaway** [comment]
@jamesmelville unfortunately have to roll this back since I wasn't able to get the related changes to the mm core merged simultaneously

fyi - there is a new node rewrite that is replacing the existing python core, this is a great feature, and would be worth it to resubmit your pull in that repo as I expect the python core is not going to take many more submissions

**Comment by jonathanwiesel** [comment]
Is there a workaround as of now for private repo templates?

**Pull request merged**
