### PR TITLE
Sounds for MavensMate

### PR DESCRIPTION
**Pull request by dkurylo**
These changes add sounds for MavensMate.

### CODE REVIEW

**Comment by ralphcallaway** [comment]
thanks @dkurylo

**Comment by ralphcallaway** [comment]
@dkurylo this is available in v4.0.4 which is current available for pre-release, thanks again for the contributions!

**Comment by dkurylo** [comment]
Nice to read that!

**Comment by dkurylo** [comment]
@ralphcallaway I've noticed that there are two "mm_play_sounds" parameters in the mavensmate default settings (mavensmate.sublime-settings), the first of them (line 130) is set to true and is used by MM instead of the second one (line 252) which is false (the value you wanted to be set by default).
Suggesting the removal of the first parameter on the line 130.

**Comment by ralphcallaway** [comment]
@dkurylo so it appears there is already some sound support, but only for the ui based commands

looks like we'll need to adjust your param, could you assist in changing your settings json key to something different, perhaps `mm_st3_play_sounds` so both can coexist? it would also help if you could add some clarifying language in the comments for the settings so users can distinguish between the two better

**Comment by dkurylo** [comment]
@ralphcallaway Sorry, I don't have the time to set up Git and create another request. But I can tell you where things are.
It's line #15 in "Sounds.py" and Line #221 in "mavensmate.sublime-settings". If both are adjusted to another value, then it will work separately from the "other" "mm_play_sounds" parameter.
Also given what you told above, I'm suggesting the removal of the "global switch; " text in line #219 of "mavensmate.sublime-settings", since it turned out that it was not global, and another switch is controlling some other part of the sounds functionality.
The comments for the switch are actually already present for that switch, and unfortunately IDK what that "other" switch is controlling, so I'm unable to properly add the comment to that one.

**Comment by ralphcallaway** [comment]
Agreed, not sure when I'll have a chance to look at this either
unfortunately. All this is done in my free time, so it comes in
unpredictable fits and bursts. If there is anyway for you to help it'd be
appreciated.

**Comment by dkurylo** [comment]
@ralphcallaway what if I just delete the second setting (the one that you've proposed to rename to mm_st3_play_sounds, and turn off the secondary notification parameters instead (by default)?
What I mean is that plugin works in such way, that if that mm_play_sounds switch is true, if checks for which types of events it is allowed to play, and which types should remain silent. So, there is another set of parameters that (dis)allows playing sounds of that type. I propose disabling these secondary parameters to disallow playing sounds of all types this pull request introduces, and removeing the duplicated mm_play_sounds parameter.
In this case there will be just one sound switch, and users will have to turn on the types of sounds they will want to be played, if any. In this case by default there will be no sounds that are introduced by this pull request played, but other will, as it was before this pull request. And the switch will be truly global, since turning it off will shut down all sound events.

**Comment by ralphcallaway** [comment]
@dkurylo that makes a lot more sense than my suggestion ...

**Comment by dkurylo** [comment]
@ralphcallaway https://github.com/joeferraro/MavensMate-SublimeText/pull/563

**Pull request merged**
